name: RuboCop

on:
  push:
    branches:
      - 'feat/*' # Somente branches que começam com 'feat/'
      - 'fix/*'  # Somente branches que começam com 'fix/'

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop and auto-correct offenses
        run: bundle exec rubocop -a