name: RuboCop

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'develop'

  workflow_dispatch:

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop and verify offenses
        run: bundle exec rubocop