name: UnitTest

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'develop'
# Após o Pull do RuboCop descomentar essas linhas.
#   workflow_run:
#     workflows: ["RuboCop"]
#     types:
#       - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec
        run: bundle exec rspec
