name: Unit Test

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'develop'
  pull_request:
    types:
      - opened

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec
        run: bundle exec rspec
